USE HockeyShop

CREATE TABLE Roles
(
		Id INT PRIMARY KEY IDENTITY,
		Name VARCHAR(100) NOT NULL
)

CREATE TABLE Users
(
		Id INT PRIMARY KEY IDENTITY,
		Role_id INT NOT NULL,
		Name VARCHAR(100) NOT NULL,
		Email VARCHAR(70) NOT NULL,
		Password VARCHAR(270) NOT NULL
		FOREIGN KEY (Role_id) REFERENCES Roles(Id) ON DELETE CASCADE,
)

CREATE TABLE User_logs
(
		Id INT PRIMARY KEY IDENTITY,
		User_id INT NOT NULL,
		Message VARCHAR(400)
		FOREIGN KEY (User_id) REFERENCES Users(Id) ON DELETE CASCADE
)

CREATE TABLE Carts
(
		Id INT PRIMARY KEY IDENTITY,
		User_id INT NOT NULL UNIQUE,
		FOREIGN KEY (User_id) REFERENCES Users(Id) ON DELETE CASCADE
)

CREATE TABLE Product_description
(
		Id INT PRIMARY KEY IDENTITY,
		Price INT NOT NULL,
		Description VARCHAR(1000) NOT NULL,
		Status VARCHAR(120) NOT NULL,
		Size VARCHAR(100) NOT NULL
)

CREATE TABLE Categories
(
		Id INT PRIMARY KEY IDENTITY,
		Name VARCHAR(100) NOT NULL
)

CREATE TABLE Manufacturer
(
		Id INT PRIMARY KEY IDENTITY,
		Name VARCHAR(100) NOT NULL 
)

CREATE TABLE Discount
(
		Id INT PRIMARY KEY IDENTITY,
		Discount INT NOT NULL DEFAULT 0
)

CREATE TABLE Products
(
		Id INT PRIMARY KEY IDENTITY,
		Category_id INT NOT NULL,
		Name VARCHAR(150) NOT NULL,
		Product_description_id INT NOT NULL UNIQUE,
		Manufacturer_id INT NOT NULL,
		Discount_id INT NOT NULL
		FOREIGN KEY (Category_id) REFERENCES Categories(Id) ON DELETE CASCADE,
		FOREIGN KEY (Product_description_id) REFERENCES Product_description(Id) ON DELETE CASCADE,
		FOREIGN KEY (Manufacturer_id) REFERENCES Manufacturer(Id) ON DELETE CASCADE,
		FOREIGN KEY (Discount_id) REFERENCES Discount(Id) ON DELETE CASCADE
)

CREATE TABLE Product_image
(
		Id INT PRIMARY KEY IDENTITY,
		Url VARCHAR(300) NOT NULL,
		Product_id INT NOT NULL
		FOREIGN KEY (Product_id) REFERENCES Products(Id) ON DELETE CASCADE
)

CREATE TABLE Carts_Products
(
		Id INT PRIMARY KEY IDENTITY,
		Cart_id INT NOT NULL,
		Product_id INT NOT NULL,
		Added_date DATE NOT NULL
		FOREIGN KEY (Product_id) REFERENCES Products(Id) ON DELETE CASCADE,
		FOREIGN KEY (Cart_id) REFERENCES Carts(Id) ON DELETE CASCADE
)

CREATE TABLE Orders
(
		Id INT PRIMARY KEY IDENTITY,
		User_id INT NOT NULL,
		Created_date DATE NOT NULL,
		Sum INT NOT NULL
		FOREIGN KEY (User_id) REFERENCES Carts(User_id) ON DELETE CASCADE
)

CREATE TABLE Orders_Products
(
		Id INT PRIMARY KEY IDENTITY,
		Order_id INT NOT NULL,
		Product_id INT NOT NULL
		FOREIGN KEY (Order_id) REFERENCES Orders(Id) ON DELETE CASCADE,
		FOREIGN KEY (Product_id) REFERENCES Products(Id) ON DELETE CASCADE
)

